framework:
    secret: '%env(APP_SECRET)%'
    validation: { enabled: true }
    php_errors:
        log: true
    default_locale: 'en'
    translator:
        fallbacks: ['en']
    csrf_protection: { enabled: true }
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session:
        # With this config, PHP's native session handling is used
        handler_id: ~
        cookie_secure: false

    #esi: ~
    #fragments: ~
