opportus_user:

    service:

        user_manager:
            id: 'opportus_user.entity_manager.user_manager.default'
            parameters: ~

        user_token_manager:
            id: 'opportus_user.entity_manager.user_token_manager.default'
            parameters: ~

        user_factory:
            id: 'opportus_user.entity_factory.user_factory.default'
            parameters:
                user_entity_class: 'App\Entity\User'

        user_token_factory:
            id: 'opportus_user.entity_factory.user_token_factory.default'
            parameters:
                user_token_entity_class: 'App\Entity\UserToken'

        user_handler:
            id: 'opportus_user.entity_handler.user_handler.default'
            parameters:
                register_user:
                    user_roles: ['ROLE_USER']
                    user_activation: false
                    user_activation_procedure: true
                proceed_user_activation:
                    user_token_activation_ttl: 24
                proceed_user_password_reset:
                    user_token_password_reset_ttl: 24

        user_mailer:
            id: 'opportus_user.mailer.user_mailer.default'
            parameters:
                send_sign_up_email:
                    from: 'noreply@snowtricks.com'
                    template: '@OpportusUser/Email/sign_up.html.twig'
                send_activate_email:
                    from: 'noreply@snowtricks.com'
                    template: '@OpportusUser/Email/activate.html.twig'
                send_reset_password_email:
                    from: 'noreply@snowtricks.com'
                    template: '@OpportusUser/Email/reset_password.html.twig'

        user_controller:
            id: 'opportus_user.controller.user_controller.default'
            parameters:
                sign_up:
                    template: '@OpportusUser/Form/sign_up.html.twig'
                    redirection:
                        success: 'index'
                        failure:
                            user_unique_constraint_violation: ~
                            unexpected: ~
                    proceed_user_activation: true
                sign_in:
                    template: '@OpportusUser/Form/sign_in.html.twig'
                activate:
                    template: ~
                    redirection:
                        success: 'index'
                        failure:
                            user_token_not_valid: 'index'
                            unexpected: 'index'
                request_reset_password:
                    template: '@OpportusUser/Form/request_reset_password.html.twig'
                    redirection:
                        success: 'index'
                        failure:
                            user_not_found: ~
                            unexpected: ~
                reset_password:
                    template: '@OpportusUser/Form/reset_password.html.twig'
                    redirection:
                        success: 'index'
                        failure:
                            user_token_not_valid: ~
                            unexpected: ~

        user_form_factory:
            id: 'opportus_user.form.factory.user_form_factory.default'
            parameters:
                create_sign_up_form:
                    user_sign_up_form_type_class: 'Opportus\UserBundle\Form\Type\UserSignUpFormType'
                create_sign_in_form:
                    user_sign_in_form_type_class: 'Opportus\UserBundle\Form\Type\UserSignInFormType'
                create_request_reset_password_form:
                    user_request_reset_password_form_type_class: 'Opportus\UserBundle\Form\Type\UserRequestResetPasswordFormType'
                create_reset_password_form:
                    user_reset_password_form_type_class: 'Opportus\UserBundle\Form\Type\UserResetPasswordFormType'

        user_password_encoder:
            id: 'opportus_user.security.user_password_encoder.default'
            parameters: ~

        user_provider:
            id: 'opportus_user.security.user_provider.default'
            parameters: ~
