security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        opportus_user_bundle:
            id: App\Security\UserProvider

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: user_sign_in
                check_path: user_sign_in
                username_parameter: 'user_sign_in[username]'
                password_parameter: 'user_sign_in[plainPassword]'
                csrf_parameter: 'user_sign_in[_token]'
            logout:
                path: user_sign_out
