# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    app_name: 'SnowTricks'
    form_theme: 'bootstrap_4_layout.html.twig'

    # Request parameters
    request_parameters:

        # Trick
        trick_get:
            template: 'trick/trick.html.twhig'
            form_options: ~

        trick_get_list:
            template: '/trick/trick_list.html.twig'
            form_options: ~

        trick_delete:
            template: ~
            form_options:
                action: 'trick_delete'
                method: 'DELETE'
                validation_groups: ['trick.delete.form']
                csrf_protection: true,
                csrf_field_name: '_token'
                csrf_token_id: 'security'

        # Trick Comment
        trick_comment_get:
            template: ~
            form_options: ~

        trick_comment_get_list:
            template: '/trick/comment/trick_comment_list.html.twig'
            form_options: ~

        trick_comment_post:
            template: ~
            form_options:
                action: 'trick_comment_post'
                method: 'POST'
                validation_groups: ['trick_comment.post.form']
                csrf_protection: true,
                csrf_field_name: '_token'
                csrf_token_id: 'security'

        trick_comment_put:
            template: ~
            form_options:
                action: 'trick_comment_put'
                method: 'PUT'
                validation_groups: ['trick_comment.put.form']
                csrf_protection: true,
                csrf_field_name: '_token'
                csrf_token_id: 'security'

        trick_comment_delete:
            template: ~
            form_options:
                action: 'trick_comment_delete'
                method: 'DELETE'
                validation_groups: ['trick_comment.delete.form']
                csrf_protection: true,
                csrf_field_name: '_token'
                csrf_token_id: 'security'

        trick_comment_get_form:
            template: 'trick/comment/trick_comment_form'
            form_options: ~

        trick_comment_get_new_form:
            template: 'trick/comment/trick_comment_form'
            form_options: ~

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Controller...
    App\Controller\HomeController:
        arguments:
            $parameters:
                '%request_parameters%'
    App\Controller\UserController:
        arguments:
            $parameters:
                '%request_parameters%'
    App\Controller\TrickController:
        arguments:
            $parameters:
                '%request_parameters%'
    App\Controller\TrickCommentController:
        arguments:
            $parameters:
                '%request_parameters%'

    # Mailer...
    App\Mailer\MailerInterface: '@App\Mailer\Mailer'
    App\Mailer\Mailer:
        arguments:
            $parameters:
                send_user_sign_up_email:
                    from: snowtricks@example.com
                    template: user/sign_up_email.html.twig
                send_user_activation_email:
                    from: snowtricks@example.com
                    template: user/activate_email.html.twig
                send_user_password_reset_email:
                    from: snowtricks@example.com
                    template: user/reset_password_email.html.twig

    # Validator...
    App\Validator\ValidatorInterface: '@App\Validator\Validator'
    App\Validator\Validator:
        arguments:
            $parameters: []

    # Event listener...

    # Event subscriber...
    App\EventSubscriber\UserPasswordEncoderSubscriber:
        tags:
            - { name: doctrine.event_listener, event: prePersist, priority: 100}
            - { name: doctrine.event_listener, event: preUpdate, priority: 100}
    App\EventSubscriber\ValidatorSubscriber:
        tags:
            - { name: doctrine.event_listener, event: prePersist, priority: 90}
            - { name: doctrine.event_listener, event: preUpdate, priority: 90}
